import { derived, readable } from 'svelte/store';

export let listOfMapsImage =  [

  'product',
  'prolands',
  'propaganda',
  'proplant',
  'prowater',
  'ramjam',
  'reckoner',
  'shiftwater',
  'snakewater',
  'summercoast',
  'sunshine',
  'upward',
  'vigil',
  'villa',
  'warmtic',
  'ashville',
  'badlads',
  'bagel',
  'ballin_comptf',
  'ballin_sky',
  'barnblitz',
  'bball_sweethills',
  'borneo',
  'cardinal',
  'cascade',
  'clearcut',
  'coalplant',
  'granary',
  'gullywash',
  'kalinka',
  'lakeside',
  'logjam',
  'mannbase',
  ]
